const fs = require('fs');

const wilayas = [
  { name: 'Alger',      code: 16, prefix: 'alg',  lat: 36.7538,  lon: 3.0588,  coastal: true  },
  { name: 'Oran',       code: 31, prefix: 'oran',  lat: 35.6969,  lon: -0.6331, coastal: true  },
  { name: 'Annaba',     code: 23, prefix: 'ann',   lat: 36.9020,  lon: 7.7574,  coastal: true  },
  { name: 'Béjaïa',    code: 6,  prefix: 'bej',   lat: 36.7509,  lon: 5.0560,  coastal: true  },
  { name: 'Tizi Ouzou', code: 15, prefix: 'tiz',   lat: 36.7169,  lon: 4.0497,  coastal: false },
  { name: 'Tlemcen',    code: 13, prefix: 'tlem',  lat: 34.8828,  lon: -1.3159, coastal: false },
];

function r(base, range) { return parseFloat((base + (Math.random() - 0.5) * range).toFixed(4)); }
function rInt(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }

// ─── RESTAURANTS ────────────────────────────────────────────────────────────

const restaurantNames = {
  'Alger': [
    ['La Casbah Gourmande','مطعم القصبة الذواقة','The Casbah Gourmet'],
    ['El Mordjane','المرجان','El Mordjane'],
    ['Dar El Kef','دار الكاف','Dar El Kef'],
    ['Restaurant Le Figaro','مطعم لو فيغارو','Le Figaro Restaurant'],
    ['La Méditerranée','المتوسط','La Méditerranée'],
    ['El Bahdja Grill','مشوي البهجة','El Bahdja Grill'],
    ['Le Carthage','قرطاج','Le Carthage'],
    ['La Terrasse d\'Alger','تراس الجزائر','La Terrasse d\'Alger'],
    ['Dar Ben Abdallah','دار بن عبد الله','Dar Ben Abdallah'],
    ['Le Panorama','البانوراما','Le Panorama'],
    ['Grill du Port','مشوي الميناء','Port Grill'],
    ['El Menzeh','المنزه','El Menzeh'],
    ['Restaurant Les Pins','مطعم الصنوبر','Les Pins Restaurant'],
    ['Brasserie des Arcades','مقهى الأقواس','Les Arcades Brasserie'],
    ['Le Patio','الفناء','Le Patio'],
    ['El Aurassi Table','مائدة الأوراسي','El Aurassi Table'],
    ['Dar Zitoun','دار الزيتون','Dar Zitoun'],
    ['Restaurant Boudjima','مطعم بوجيمة','Boudjima Restaurant'],
    ['La Villa Méditerranée','فيلا المتوسط','La Villa Méditerranée'],
    ['Le Bosphore d\'Alger','بوسفور الجزائر','Le Bosphore d\'Alger'],
  ],
  'Oran': [
    ['El Bahia Restaurant','مطعم الباهية','El Bahia Restaurant'],
    ['La Pergola d\'Oran','برغولا وهران','La Pergola d\'Oran'],
    ['Dar Diaf Oran','دار الضيف وهران','Dar Diaf Oran'],
    ['Le Santa Cruz','سانتا كروز','Le Santa Cruz'],
    ['Restaurant Murdjadjo','مطعم مرجاجو','Murdjadjo Restaurant'],
    ['El Hamra Oran','الحمراء وهران','El Hamra Oran'],
    ['Grill La Corniche','مشوي الكورنيش','Corniche Grill'],
    ['L\'Andalou d\'Oran','الأندلسي وهران','L\'Andalou d\'Oran'],
    ['Le Méridien Table','مائدة المريديان','Le Méridien Table'],
    ['Restaurant Les Platanes','مطعم البلاطان','Les Platanes Restaurant'],
    ['El Mokhtar Oran','المختار وهران','El Mokhtar Oran'],
    ['La Caravelle','الكارافيل','La Caravelle'],
    ['Dar El Bey Oran','دار البايات وهران','Dar El Bey Oran'],
    ['Le Casablanca','كازابلانكا','Le Casablanca'],
    ['Restaurant Sidi El Houari','مطعم سيدي الهواري','Sidi El Houari Restaurant'],
    ['Le Versailles d\'Oran','فيرساي وهران','Le Versailles d\'Oran'],
    ['El Khaima Grill','مشوي الخيمة','El Khaima Grill'],
    ['La Médina d\'Oran','مدينة وهران','La Médina d\'Oran'],
    ['Brasserie Tafna','براسري تافنة','Tafna Brasserie'],
    ['Restaurant Cap Falcon','مطعم كاب فالكون','Cap Falcon Restaurant'],
  ],
  'Annaba': [
    ['Restaurant Seybouse','مطعم سيبوس','Seybouse Restaurant'],
    ['El Hadj Annabi','الحاج العنابي','El Hadj Annabi'],
    ['La Corniche d\'Annaba','كورنيش عنابة','Annaba Corniche Restaurant'],
    ['Dar Beida Annaba','الدار البيضاء عنابة','Dar Beida Annaba'],
    ['Le Saint-Cloud','سان كلو','Le Saint-Cloud'],
    ['Restaurant Hippone','مطعم هيبون','Hippone Restaurant'],
    ['El Kantara Annaba','القنطرة عنابة','El Kantara Annaba'],
    ['Grill El Bouni','مشوي البوني','El Bouni Grill'],
    ['La Caravelle d\'Annaba','كارافيل عنابة','La Caravelle d\'Annaba'],
    ['Le Rif Annaba','ريف عنابة','Le Rif Annaba'],
    ['Restaurant Jijel Gate','مطعم باب جيجل','Jijel Gate Restaurant'],
    ['El Minzah Annaba','المنزه عنابة','El Minzah Annaba'],
    ['Dar El Djamel','دار الجمال','Dar El Djamel'],
    ['Le Palmier d\'Annaba','نخيل عنابة','Le Palmier d\'Annaba'],
    ['Restaurant Ain Achir','مطعم عين أشير','Ain Achir Restaurant'],
    ['El Nakhla Annaba','النخلة عنابة','El Nakhla Annaba'],
    ['La Bonne Table','المائدة الجيدة','La Bonne Table'],
    ['Restaurant Edough','مطعم إيدوغ','Edough Restaurant'],
    ['Le Phare d\'Annaba','منارة عنابة','Le Phare d\'Annaba'],
    ['Dar Zouaoui Annaba','دار زواوي عنابة','Dar Zouaoui Annaba'],
  ],
  'Béjaïa': [
    ['Restaurant Yemma Gouraya','مطعم يمة قورايا','Yemma Gouraya Restaurant'],
    ['El Bahri Béjaïa','البحري بجاية','El Bahri Béjaïa'],
    ['Dar Sour El Ghozlane','دار سور الغزلان بجاية','Dar Sour El Ghozlane'],
    ['Le Cap Carbon','كاب كربون','Le Cap Carbon'],
    ['Restaurant Aokas','مطعم أوقاس','Aokas Restaurant'],
    ['El Djamour Béjaïa','الجامور بجاية','El Djamour Béjaïa'],
    ['La Perle de Béjaïa','لؤلؤة بجاية','La Perle de Béjaïa'],
    ['Grill Tichy','مشوي تيشي','Tichy Grill'],
    ['Dar Amizour','دار أميزور','Dar Amizour'],
    ['Restaurant Soummam','مطعم الصومام','Soummam Restaurant'],
    ['Le Phare de Béjaïa','منارة بجاية','Le Phare de Béjaïa'],
    ['El Boulevar Béjaïa','البولفار بجاية','El Boulevar Béjaïa'],
    ['La Kabylie Gourmande','القبائل الذواقة','La Kabylie Gourmande'],
    ['Restaurant Bejaia Palace','مطعم بجاية بالاس','Bejaia Palace Restaurant'],
    ['El Aouche Béjaïa','العوش بجاية','El Aouche Béjaïa'],
    ['Dar Tafza','دار تافزة','Dar Tafza'],
    ['Restaurant Oued Ghir','مطعم واد غير','Oued Ghir Restaurant'],
    ['Le Jardin de Béjaïa','حديقة بجاية','Le Jardin de Béjaïa'],
    ['El Ferdaous Béjaïa','الفردوس بجاية','El Ferdaous Béjaïa'],
    ['Brasserie Bejaia Bay','براسري خليج بجاية','Bejaia Bay Brasserie'],
  ],
  'Tizi Ouzou': [
    ['Restaurant Tafat','مطعم تافات','Tafat Restaurant'],
    ['Dar Amrouche Tizi','دار عمروش تيزي','Dar Amrouche Tizi'],
    ['El Djurdjura Table','مائدة الجرجرة','El Djurdjura Table'],
    ['La Kabylie Tizi','قبيلة تيزي وزو','La Kabylie Tizi'],
    ['Restaurant Ath Yenni','مطعم آث يني','Ath Yenni Restaurant'],
    ['Grill Tizi Centre','مشوي وسط تيزي','Tizi Centre Grill'],
    ['El Bourak Tizi Ouzou','البوراق تيزي وزو','El Bourak Tizi Ouzou'],
    ['Dar Tafsut','دار تافسوت','Dar Tafsut'],
    ['Restaurant Irdjen','مطعم إيرجن','Irdjen Restaurant'],
    ['Le Chêne Tizi Ouzou','البلوط تيزي وزو','Le Chêne Tizi Ouzou'],
    ['El Marsa Tizi','المرسى تيزي','El Marsa Tizi'],
    ['La Montagne Kabyle','الجبل القبائلي','La Montagne Kabyle'],
    ['Restaurant Boghni','مطعم بوغني','Boghni Restaurant'],
    ['Dar Ziryab Tizi','دار زرياب تيزي','Dar Ziryab Tizi'],
    ['El Figuier Tizi Ouzou','التين تيزي وزو','El Figuier Tizi Ouzou'],
    ['Restaurant Makouda','مطعم ماقودة','Makouda Restaurant'],
    ['Le Tamgout','تامقوت','Le Tamgout'],
    ['Dar Leqbayel','دار لقبايل','Dar Leqbayel'],
    ['Restaurant Draa Ben Khedda','مطعم ذراع بن خدة','Draa Ben Khedda Restaurant'],
    ['El Hamdani Tizi Ouzou','الحمداني تيزي وزو','El Hamdani Tizi Ouzou'],
  ],
  'Tlemcen': [
    ['Restaurant Dar El Bacha','مطعم دار الباشا','Dar El Bacha Restaurant'],
    ['El Mansourah Table','مائدة المنصورة','El Mansourah Table'],
    ['La Cité Andalouse','المدينة الأندلسية','La Cité Andalouse'],
    ['Dar Soltane Tlemcen','دار السلطان تلمسان','Dar Soltane Tlemcen'],
    ['Restaurant Lalla Setti','مطعم لالة ستي','Lalla Setti Restaurant'],
    ['El Méchouar Grill','مشوي المشوار','El Méchouar Grill'],
    ['La Tlemcenoise','التلمسانية','La Tlemcenoise'],
    ['Dar Zianide','دار الزيانيين','Dar Zianide'],
    ['Restaurant Ain Fezza','مطعم عين الفضة','Ain Fezza Restaurant'],
    ['El Kalaa Tlemcen','القلعة تلمسان','El Kalaa Tlemcen'],
    ['Le Grenadier Tlemcen','الرمان تلمسان','Le Grenadier Tlemcen'],
    ['Dar Sid El Haloui','دار سيدي الهاللوي','Dar Sid El Haloui'],
    ['Restaurant Remchi','مطعم رمشي','Remchi Restaurant'],
    ['El Andalous Tlemcen','الأندلسي تلمسان','El Andalous Tlemcen'],
    ['La Table des Zianides','مائدة الزيانيين','La Table des Zianides'],
    ['Restaurant Nedroma','مطعم ندرومة','Nedroma Restaurant'],
    ['Dar Bensekran Tlemcen','دار بن سكران تلمسان','Dar Bensekran Tlemcen'],
    ['Le Mechoui Royal','المشوي الملكي','Le Mechoui Royal'],
    ['Restaurant Maghnia','مطعم مغنية','Maghnia Restaurant'],
    ['El Hafsia Tlemcen','الحفصية تلمسان','El Hafsia Tlemcen'],
  ],
};

// ─── SALONS / CAFÉS ─────────────────────────────────────────────────────────

const salonNames = {
  'Alger': [
    ['Café Glacier Alger','مقهى جلاسيي الجزائر','Café Glacier Alger'],
    ['Salon de thé El Bahdja','صالون شاي البهجة','El Bahdja Tea Salon'],
    ['Café des Facultés','مقهى الكليات','Café des Facultés'],
    ['Le Kiosque d\'Alger','كيوسك الجزائر','Le Kiosque d\'Alger'],
    ['Salon Dar El Djamil','صالون دار الجميل','Salon Dar El Djamil'],
    ['Café El Mordjane','مقهى المرجان','Café El Mordjane'],
    ['La Baguette & Café','الباكيت والقهوة','La Baguette & Café'],
    ['Salon de thé Palma','صالون شاي بالما','Palma Tea Salon'],
    ['Café Ryadh El Feth','مقهى رياض الفتح','Café Ryadh El Feth'],
    ['Le Grand Café d\'Alger','المقهى الكبير بالجزائر','Le Grand Café d\'Alger'],
    ['Salon El Warda Alger','صالون الوردة الجزائر','El Warda Salon Alger'],
    ['Café Bab El Oued','مقهى باب الواد','Café Bab El Oued'],
    ['Le Café des Arts','مقهى الفنون','Café des Arts'],
    ['Salon Tassili Alger','صالون تسيلي الجزائر','Tassili Salon Alger'],
    ['Café Kouba','مقهى قوبة','Café Kouba'],
    ['Le Pâtissier d\'Alger','حلواني الجزائر','Le Pâtissier d\'Alger'],
    ['Salon El Yasmine Alger','صالون الياسمين الجزائر','El Yasmine Salon Alger'],
    ['Café Bouzaréah','مقهى بوزريعة','Café Bouzaréah'],
    ['Le Salon du Thé Hydra','صالون شاي حيدرة','Hydra Tea Salon'],
    ['Café Pins Maritimes','مقهى الصنوبر البحري','Café Pins Maritimes'],
  ],
  'Oran': [
    ['Café Bahia d\'Oran','مقهى باهية وهران','Café Bahia d\'Oran'],
    ['Salon de thé El Hamri','صالون شاي الحمري','El Hamri Tea Salon'],
    ['Le Grand Café Oran','المقهى الكبير وهران','Le Grand Café Oran'],
    ['Café Sidi El Houari','مقهى سيدي الهواري','Café Sidi El Houari'],
    ['Salon El Ghazal Oran','صالون الغزال وهران','El Ghazal Salon Oran'],
    ['Café la Corniche Oran','مقهى كورنيش وهران','Café la Corniche Oran'],
    ['Le Kiosque d\'Oran','كيوسك وهران','Le Kiosque d\'Oran'],
    ['Salon de thé Murdjadjo','صالون شاي مرجاجو','Murdjadjo Tea Salon'],
    ['Café Choupot','مقهى شوبو','Café Choupot'],
    ['La Pâtisserie d\'Oran','حلواني وهران','La Pâtisserie d\'Oran'],
    ['Café El Menzah Oran','مقهى المنزه وهران','Café El Menzah Oran'],
    ['Salon Tafna','صالون تافنة','Salon Tafna'],
    ['Le Café des Oliviers','مقهى الزيتون','Café des Oliviers'],
    ['Salon El Andalous Oran','صالون الأندلسي وهران','El Andalous Salon Oran'],
    ['Café Plateau St Michel','مقهى سان ميشيل','Café Plateau St Michel'],
    ['Le Brûlot d\'Oran','البرولو وهران','Le Brûlot d\'Oran'],
    ['Salon de thé El Warda Oran','صالون شاي الوردة وهران','El Warda Tea Salon Oran'],
    ['Café Es Sénia','مقهى السانية','Café Es Sénia'],
    ['La Pause Oranaise','الاستراحة الوهرانية','La Pause Oranaise'],
    ['Café Bel Horizon Oran','مقهى بيل هوريزون وهران','Café Bel Horizon Oran'],
  ],
  'Annaba': [
    ['Café Annabi Centre','مقهى عنابي وسط','Café Annabi Centre'],
    ['Salon de thé Seybouse','صالون شاي سيبوس','Seybouse Tea Salon'],
    ['Le Grand Café d\'Annaba','المقهى الكبير عنابة','Le Grand Café d\'Annaba'],
    ['Café El Kantara Annaba','مقهى القنطرة عنابة','Café El Kantara Annaba'],
    ['Salon El Bouni','صالون البوني','Salon El Bouni'],
    ['Café de la Corniche Annaba','مقهى كورنيش عنابة','Café de la Corniche Annaba'],
    ['La Pâtisserie Annabie','الحلواني العنابية','La Pâtisserie Annabie'],
    ['Salon de thé Hippone','صالون شاي هيبون','Hippone Tea Salon'],
    ['Café Place du 1er Novembre','مقهى ساحة أول نوفمبر','Café Place 1er Novembre'],
    ['Le Kiosque d\'Annaba','كيوسك عنابة','Le Kiosque d\'Annaba'],
    ['Salon El Yasmine Annaba','صالون الياسمين عنابة','El Yasmine Salon Annaba'],
    ['Café Ain Achir','مقهى عين أشير','Café Ain Achir'],
    ['Le Salon du Lac Fetzara','صالون بحيرة فتزارة','Lac Fetzara Salon'],
    ['Café Sidi Salem Annaba','مقهى سيدي سالم عنابة','Café Sidi Salem Annaba'],
    ['La Pause Annabie','الاستراحة العنابية','La Pause Annabie'],
    ['Salon de thé El Boustane','صالون شاي البستان','El Boustane Tea Salon'],
    ['Café Oued El Anneb','مقهى واد العناب','Café Oued El Anneb'],
    ['Le Glacier d\'Annaba','جلاسيي عنابة','Le Glacier d\'Annaba'],
    ['Café El Hadj Annaba','مقهى الحاج عنابة','Café El Hadj Annaba'],
    ['Salon des Arts Annaba','صالون الفنون عنابة','Salon des Arts Annaba'],
  ],
  'Béjaïa': [
    ['Café Gouraya Béjaïa','مقهى قورايا بجاية','Café Gouraya Béjaïa'],
    ['Salon de thé Cap Carbon','صالون شاي كاب كربون','Cap Carbon Tea Salon'],
    ['Le Grand Café de Béjaïa','المقهى الكبير بجاية','Le Grand Café de Béjaïa'],
    ['Café El Kherba Béjaïa','مقهى الخربة بجاية','Café El Kherba Béjaïa'],
    ['Salon de thé Soummam','صالون شاي الصومام','Soummam Tea Salon'],
    ['Café Tichy Plage','مقهى شاطئ تيشي','Café Tichy Plage'],
    ['La Pâtisserie Kabyle','الحلواني القبائلي','La Pâtisserie Kabyle'],
    ['Salon El Kef Béjaïa','صالون الكاف بجاية','El Kef Salon Béjaïa'],
    ['Café Bord de Mer Béjaïa','مقهى البحر بجاية','Café Bord de Mer Béjaïa'],
    ['Le Kiosque de Béjaïa','كيوسك بجاية','Le Kiosque de Béjaïa'],
    ['Salon Aokas Plage','صالون شاطئ أوقاس','Aokas Plage Salon'],
    ['Café Oued Ghir','مقهى واد غير','Café Oued Ghir'],
    ['Le Café des Oliviers Béjaïa','مقهى الزيتون بجاية','Café des Oliviers Béjaïa'],
    ['Salon de thé El Merdja','صالون شاي المرجة','El Merdja Tea Salon'],
    ['Café Sidi Ahmed Béjaïa','مقهى سيدي أحمد بجاية','Café Sidi Ahmed Béjaïa'],
    ['La Pause Kabyle','الاستراحة القبائلية','La Pause Kabyle'],
    ['Salon Amirouche Béjaïa','صالون عميروش بجاية','Salon Amirouche Béjaïa'],
    ['Café El Djemaa Béjaïa','مقهى الجمعة بجاية','Café El Djemaa Béjaïa'],
    ['Le Glacier de Béjaïa','جلاسيي بجاية','Le Glacier de Béjaïa'],
    ['Café Ighzer Béjaïa','مقهى إغزر بجاية','Café Ighzer Béjaïa'],
  ],
  'Tizi Ouzou': [
    ['Café Tafat Tizi','مقهى تافات تيزي','Café Tafat Tizi'],
    ['Salon de thé Djurdjura','صالون شاي الجرجرة','Djurdjura Tea Salon'],
    ['Le Grand Café de Tizi','المقهى الكبير تيزي','Le Grand Café de Tizi'],
    ['Café Oued Aissi','مقهى واد عيسي','Café Oued Aissi'],
    ['Salon El Warda Tizi','صالون الوردة تيزي','El Warda Salon Tizi'],
    ['Café Boghni Centre','مقهى وسط بوغني','Café Boghni Centre'],
    ['La Pâtisserie Kabyle Tizi','الحلواني القبائلي تيزي','La Pâtisserie Kabyle Tizi'],
    ['Salon de thé Tamgout','صالون شاي تامقوت','Tamgout Tea Salon'],
    ['Café Draa Ben Khedda','مقهى ذراع بن خدة','Café Draa Ben Khedda'],
    ['Le Kiosque de Tizi','كيوسك تيزي','Le Kiosque de Tizi'],
    ['Salon Ath Yenni Tizi','صالون آث يني تيزي','Salon Ath Yenni Tizi'],
    ['Café Makouda','مقهى ماقودة','Café Makouda'],
    ['Le Café de la Montagne','مقهى الجبل','Café de la Montagne'],
    ['Salon de thé Tigzirt','صالون شاي تيقزيرت','Tigzirt Tea Salon'],
    ['Café Azzazga','مقهى عزازقة','Café Azzazga'],
    ['La Pause Kabyle Tizi','الاستراحة القبائلية تيزي','La Pause Kabyle Tizi'],
    ['Salon Beni Yenni','صالون بني يني','Salon Beni Yenni'],
    ['Café Fréha Tizi','مقهى فريحة تيزي','Café Fréha Tizi'],
    ['Le Glacier de Tizi Ouzou','جلاسيي تيزي وزو','Le Glacier de Tizi Ouzou'],
    ['Café Mekla Tizi','مقهى مقلع تيزي','Café Mekla Tizi'],
  ],
  'Tlemcen': [
    ['Café El Andalous Tlemcen','مقهى الأندلسي تلمسان','Café El Andalous Tlemcen'],
    ['Salon de thé Mansourah','صالون شاي المنصورة','Mansourah Tea Salon'],
    ['Le Grand Café de Tlemcen','المقهى الكبير تلمسان','Le Grand Café de Tlemcen'],
    ['Café Sidi Boumediene Tlemcen','مقهى سيدي بومدين تلمسان','Café Sidi Boumediene Tlemcen'],
    ['Salon El Mechouar','صالون المشوار','Salon El Mechouar'],
    ['Café Ain Fezza','مقهى عين الفضة','Café Ain Fezza'],
    ['La Pâtisserie Tlemcenoise','الحلواني التلمسانية','La Pâtisserie Tlemcenoise'],
    ['Salon de thé El Eubbad','صالون شاي العباد','El Eubbad Tea Salon'],
    ['Café Place Khemisti','مقهى ساحة الخميستي','Café Place Khemisti'],
    ['Le Kiosque de Tlemcen','كيوسك تلمسان','Le Kiosque de Tlemcen'],
    ['Salon El Kalaa Tlemcen','صالون القلعة تلمسان','El Kalaa Salon Tlemcen'],
    ['Café Nedroma Tlemcen','مقهى ندرومة تلمسان','Café Nedroma Tlemcen'],
    ['Le Café Zianide','مقهى الزيانيين','Café Zianide'],
    ['Salon de thé Remchi','صالون شاي رمشي','Remchi Tea Salon'],
    ['Café Maghnia Centre','مقهى وسط مغنية','Café Maghnia Centre'],
    ['La Pause Tlemcenoise','الاستراحة التلمسانية','La Pause Tlemcenoise'],
    ['Salon Beni Snous','صالون بني سنوس','Salon Beni Snous'],
    ['Café Sebdou Tlemcen','مقهى سبدو تلمسان','Café Sebdou Tlemcen'],
    ['Le Glacier de Tlemcen','جلاسيي تلمسان','Le Glacier de Tlemcen'],
    ['Café El Ghabra Tlemcen','مقهى الغابرة تلمسان','Café El Ghabra Tlemcen'],
  ],
};

// ─── ARTISANAT ───────────────────────────────────────────────────────────────

const artisanatNames = {
  'Alger': [
    ['Galerie Artisanale du Plateau','معرض حرفي الهضبة','Plateau Craft Gallery','bijouterie'],
    ['Maison des Potiers d\'Alger','دار الفخارين بالجزائر','Alger Potters House','poterie'],
    ['Atelier Tissage El Bahdja','ورشة نسيج البهجة','El Bahdja Weaving Workshop','tissage'],
    ['Broderie d\'Art Algérois','تطريز فني جزائري','Algerian Art Embroidery','broderie'],
    ['Maroquinerie Casbah Alger','جلدية القصبة الجزائر','Casbah Leather Alger','maroquinerie'],
    ['Ébénisterie Dar El Kef Alger','نجارة دار الكاف الجزائر','Dar El Kef Woodwork Alger','boiserie'],
    ['Dinanderie du Vieux Alger','صناعة نحاسية قديم الجزائر','Old Algiers Copperwork','dinanderie'],
    ['Vannerie Artisanale Alger','سلة حرفية الجزائر','Alger Craft Basketry','vannerie'],
    ['Vêtements Traditionnels Alger','ملابس تقليدية الجزائر','Traditional Clothing Alger','vetements'],
    ['Zellige d\'Alger Moderne','زليج الجزائر الحديث','Modern Alger Zellige','zellige'],
    ['Parfumerie El Yasmine Alger','عطارة الياسمين الجزائر','El Yasmine Perfumery Alger','parfumerie'],
    ['Produits du Terroir Algérois','منتجات محلية جزائرية','Local Alger Products','produits'],
    ['Atelier Bijoux Bab El Oued','ورشة مجوهرات باب الواد','Bab El Oued Jewellery Workshop','bijouterie'],
    ['Céramique Artisanale Kouba','سيراميك حرفي قوبة','Kouba Craft Ceramics','poterie'],
    ['Soieries et Broderies Alger','حرير وتطريز الجزائر','Silks & Embroidery Alger','broderie'],
    ['Cuirs d\'Art Hydra','جلود فنية حيدرة','Hydra Art Leathers','maroquinerie'],
    ['Boiserie Sculptée El Biar','خشب منحوت الأبيار','El Biar Carved Woodwork','boiserie'],
    ['Cuivres du Marché Alger','نحاسيات سوق الجزائر','Alger Market Copperware','dinanderie'],
    ['Robes Kabyles Modernisées','فساتين قبائلية عصرية','Modern Kabyle Dresses','vetements'],
    ['Bijouterie Contemporaine Alger','مجوهرات معاصرة الجزائر','Contemporary Jewellery Alger','bijouterie'],
  ],
  'Oran': [
    ['Bijouterie Andalouse Oran','مجوهرات أندلسية وهران','Andalusian Jewellery Oran','bijouterie'],
    ['Poterie de Tlemcen Gate Oran','فخار باب تلمسان وهران','Tlemcen Gate Pottery Oran','poterie'],
    ['Tissage El Hamri Oran','نسيج الحمري وهران','El Hamri Weaving Oran','tissage'],
    ['Broderie Oranaise','تطريز وهراني','Oran Embroidery','broderie'],
    ['Maroquinerie Sidi El Houari','جلدية سيدي الهواري','Sidi El Houari Leatherwork','maroquinerie'],
    ['Ébénisterie Andalouse Oran','نجارة أندلسية وهران','Andalusian Woodwork Oran','boiserie'],
    ['Dinanderie Oranaise','صناعة نحاسية وهرانية','Oran Copperwork','dinanderie'],
    ['Vannerie Artisanale Oran','سلة حرفية وهران','Oran Craft Basketry','vannerie'],
    ['Vêtements Traditionnels Oran','ملابس تقليدية وهران','Traditional Clothing Oran','vetements'],
    ['Zellige de la Médina Oran','زليج مدينة وهران','Oran Medina Zellige','zellige'],
    ['Parfumerie des Épices Oran','عطارة التوابل وهران','Oran Spice Perfumery','parfumerie'],
    ['Souk El Hamel Oran','سوق الهامل وهران','Souk El Hamel Oran','produits'],
    ['Atelier Bijoux Murdjadjo','ورشة مجوهرات مرجاجو','Murdjadjo Jewellery Workshop','bijouterie'],
    ['Céramique Oranaise','سيراميك وهراني','Oran Ceramics','poterie'],
    ['Soieries Oranaises','حرير وهراني','Oran Silks','tissage'],
    ['Cuirs Art Oran','جلود فنية وهران','Oran Art Leathers','maroquinerie'],
    ['Marqueterie Oran','ترصيع خشبي وهران','Oran Marquetry','boiserie'],
    ['Cuivres Marché Oran','نحاسيات سوق وهران','Oran Market Copperware','dinanderie'],
    ['Robes Oranaises Brodées','فساتين وهرانية مطرزة','Embroidered Oran Dresses','vetements'],
    ['Galerie Artisanale Oran Centre','معرض حرفي وسط وهران','Oran Centre Craft Gallery','divers'],
  ],
  'Annaba': [
    ['Bijouterie Romaine Annaba','مجوهرات رومانية عنابة','Roman Jewellery Annaba','bijouterie'],
    ['Poterie Hippone Annaba','فخار هيبون عنابة','Hippone Pottery Annaba','poterie'],
    ['Tissage Seybouse Annaba','نسيج سيبوس عنابة','Seybouse Weaving Annaba','tissage'],
    ['Broderie Chaoui Annaba','تطريز شاوي عنابة','Chaoui Embroidery Annaba','broderie'],
    ['Maroquinerie El Bouni','جلدية البوني','El Bouni Leatherwork','maroquinerie'],
    ['Ébénisterie Annaba Est','نجارة شرق عنابة','East Annaba Woodwork','boiserie'],
    ['Dinanderie Annabaise','صناعة نحاسية عنابية','Annaba Copperwork','dinanderie'],
    ['Produits du Terroir Annaba','منتجات محلية عنابة','Annaba Local Products','produits'],
    ['Vêtements Traditionnels Annaba','ملابس تقليدية عنابة','Traditional Clothing Annaba','vetements'],
    ['Galerie Crafts Annaba','معرض حرف عنابة','Annaba Crafts Gallery','divers'],
    ['Atelier Bijoux Seybouse','ورشة مجوهرات سيبوس','Seybouse Jewellery Workshop','bijouterie'],
    ['Céramique Annabaise','سيراميك عنابية','Annaba Ceramics','poterie'],
    ['Soieries Annaba Est','حرير شرق عنابة','East Annaba Silks','tissage'],
    ['Cuirs Art Annaba','جلود فنية عنابة','Annaba Art Leathers','maroquinerie'],
    ['Marqueterie Annaba','ترصيع خشبي عنابة','Annaba Marquetry','boiserie'],
    ['Cuivres Artisanaux Annaba','نحاسيات حرفية عنابة','Annaba Craft Copperware','dinanderie'],
    ['Robes Traditionnelles Annaba','فساتين تقليدية عنابة','Traditional Dresses Annaba','vetements'],
    ['Parfumerie Annaba Jujube','عطارة عنابة بالعناب','Annaba Jujube Perfumery','parfumerie'],
    ['Vannerie du Nordest','سلة الشمال الشرقي','North-East Basketry','vannerie'],
    ['Souk Artisanal Annaba','سوق الحرف عنابة','Annaba Craft Souk','divers'],
  ],
  'Béjaïa': [
    ['Bijouterie Kabyle Béjaïa','مجوهرات قبائلية بجاية','Kabyle Jewellery Béjaïa','bijouterie'],
    ['Poterie Soummam Béjaïa','فخار الصومام بجاية','Soummam Pottery Béjaïa','poterie'],
    ['Tissage Kabyle Béjaïa','نسيج قبائلي بجاية','Kabyle Weaving Béjaïa','tissage'],
    ['Broderie Kabyle Béjaïa','تطريز قبائلي بجاية','Kabyle Embroidery Béjaïa','broderie'],
    ['Maroquinerie Gouraya','جلدية قورايا','Gouraya Leatherwork','maroquinerie'],
    ['Ébénisterie Béjaïa','نجارة بجاية','Béjaïa Woodwork','boiserie'],
    ['Dinanderie Béjaïe','صناعة نحاسية بجاية','Béjaïa Copperwork','dinanderie'],
    ['Vannerie Kabyle Béjaïa','سلة قبائلية بجاية','Kabyle Basketry Béjaïa','vannerie'],
    ['Vêtements Kabyles Béjaïa','ملابس قبائلية بجاية','Kabyle Clothing Béjaïa','vetements'],
    ['Galerie Crafts Béjaïa','معرض حرف بجاية','Béjaïa Crafts Gallery','divers'],
    ['Atelier Bijoux Ath Yiraten','ورشة مجوهرات آث يراتن','Ath Yiraten Jewellery Workshop','bijouterie'],
    ['Céramique Kabyle Béjaïa','سيراميك قبائلي بجاية','Kabyle Ceramics Béjaïa','poterie'],
    ['Soieries Kabyles','حرير قبائلي','Kabyle Silks','tissage'],
    ['Cuirs Art Béjaïa','جلود فنية بجاية','Béjaïa Art Leathers','maroquinerie'],
    ['Marqueterie Béjaïa','ترصيع خشبي بجاية','Béjaïa Marquetry','boiserie'],
    ['Cuivres Béjaïa','نحاسيات بجاية','Béjaïa Copperware','dinanderie'],
    ['Robes Kabyles Béjaïa','فساتين قبائلية بجاية','Kabyle Dresses Béjaïa','vetements'],
    ['Parfumerie Kabyle','عطارة قبائلية','Kabyle Perfumery','parfumerie'],
    ['Produits Bio Kabyles','منتجات عضوية قبائلية','Kabyle Organic Products','produits'],
    ['Souk Artisanal Béjaïa','سوق الحرف بجاية','Béjaïa Craft Souk','divers'],
  ],
  'Tizi Ouzou': [
    ['Bijouterie Ath Yenni Tizi','مجوهرات آث يني تيزي','Ath Yenni Jewellery Tizi','bijouterie'],
    ['Poterie Kabyle Tizi','فخار قبائلي تيزي','Kabyle Pottery Tizi','poterie'],
    ['Tissage Kabyle Tizi','نسيج قبائلي تيزي','Kabyle Weaving Tizi','tissage'],
    ['Broderie Kabyle Tizi','تطريز قبائلي تيزي','Kabyle Embroidery Tizi','broderie'],
    ['Maroquinerie Tizi Ouzou','جلدية تيزي وزو','Tizi Ouzou Leatherwork','maroquinerie'],
    ['Ébénisterie Kabyle Tizi','نجارة قبائلية تيزي','Kabyle Woodwork Tizi','boiserie'],
    ['Dinanderie Kabyle Tizi','صناعة نحاسية قبائلية تيزي','Kabyle Copperwork Tizi','dinanderie'],
    ['Vannerie Kabyle Tizi','سلة قبائلية تيزي','Kabyle Basketry Tizi','vannerie'],
    ['Vêtements Kabyles Tizi','ملابس قبائلية تيزي','Kabyle Clothing Tizi','vetements'],
    ['Galerie Crafts Tizi','معرض حرف تيزي','Tizi Crafts Gallery','divers'],
    ['Atelier Taos Amrouche','ورشة تاوس عمروش','Taos Amrouche Workshop','broderie'],
    ['Céramique Kabyle Tizi','سيراميك قبائلي تيزي','Kabyle Ceramics Tizi','poterie'],
    ['Soieries Kabyles Tizi','حرير قبائلي تيزي','Kabyle Silks Tizi','tissage'],
    ['Cuirs Kabyles Tizi','جلود قبائلية تيزي','Kabyle Leathers Tizi','maroquinerie'],
    ['Marqueterie Kabyle Tizi','ترصيع خشبي قبائلي تيزي','Kabyle Marquetry Tizi','boiserie'],
    ['Cuivres Kabyles Tizi','نحاسيات قبائلية تيزي','Kabyle Copperware Tizi','dinanderie'],
    ['Robes Kabyles Tizi','فساتين قبائلية تيزي','Kabyle Dresses Tizi','vetements'],
    ['Parfumerie Kabyle Tizi','عطارة قبائلية تيزي','Kabyle Perfumery Tizi','parfumerie'],
    ['Produits Bio Tizi','منتجات عضوية تيزي','Organic Products Tizi','produits'],
    ['Souk Artisanal Tizi','سوق الحرف تيزي','Tizi Craft Souk','divers'],
  ],
  'Tlemcen': [
    ['Bijouterie Andalouse Tlemcen 2','مجوهرات أندلسية تلمسان 2','Andalusian Jewellery Tlemcen 2','bijouterie'],
    ['Poterie Zianide Tlemcen','فخار زياني تلمسان','Zianide Pottery Tlemcen','poterie'],
    ['Tissage Tlemcenois','نسيج تلمساني','Tlemcen Weaving','tissage'],
    ['Broderie Tlemcenoise','تطريز تلمساني','Tlemcen Embroidery','broderie'],
    ['Maroquinerie Tlemcen Centre','جلدية وسط تلمسان','Tlemcen Centre Leatherwork','maroquinerie'],
    ['Ébénisterie Tlemcenoise','نجارة تلمسانية','Tlemcen Woodwork','boiserie'],
    ['Dinanderie Tlemcenoise','صناعة نحاسية تلمسانية','Tlemcen Copperwork','dinanderie'],
    ['Vannerie Tlemcenoise','سلة تلمسانية','Tlemcen Basketry','vannerie'],
    ['Vêtements Traditionnels Tlemcen 2','ملابس تقليدية تلمسان 2','Traditional Clothing Tlemcen 2','vetements'],
    ['Zellige de Tlemcen 2','زليج تلمسان 2','Tlemcen Zellige 2','zellige'],
    ['Parfumerie Andalouse Tlemcen','عطارة أندلسية تلمسان','Andalusian Perfumery Tlemcen','parfumerie'],
    ['Souk El Bali Tlemcen','سوق البالي تلمسان','Souk El Bali Tlemcen','produits'],
    ['Atelier Bijoux Sidi Boumediene','ورشة مجوهرات سيدي بومدين','Sidi Boumediene Jewellery Workshop','bijouterie'],
    ['Céramique Tlemcenoise','سيراميك تلمسانية','Tlemcen Ceramics','poterie'],
    ['Soieries Tlemcenoise','حرير تلمساني','Tlemcen Silks','tissage'],
    ['Cuirs Art Tlemcen','جلود فنية تلمسان','Tlemcen Art Leathers','maroquinerie'],
    ['Marqueterie Tlemcen','ترصيع خشبي تلمسان','Tlemcen Marquetry','boiserie'],
    ['Cuivres Marché Tlemcen','نحاسيات سوق تلمسان','Tlemcen Market Copperware','dinanderie'],
    ['Robes Tlemceniennes','فساتين تلمسانية','Tlemcen Dresses','vetements'],
    ['Galerie Artisanale Tlemcen','معرض حرفي تلمسان','Tlemcen Craft Gallery','divers'],
  ],
};

// ─── PLAGES ──────────────────────────────────────────────────────────────────

const plageNames = {
  'Alger': [
    ['Plage de Aïn Taya','شاطئ عين طاية','Aïn Taya Beach'],
    ['Plage Club des Pins','شاطئ نادي الصنوبر','Club des Pins Beach'],
    ['Plage de Moretti','شاطئ موريتي','Moretti Beach'],
    ['Plage de Zéralda','شاطئ الزرالدة','Zéralda Beach'],
    ['Plage de Bains Romains','شاطئ الحمامات الرومانية','Bains Romains Beach'],
    ['Plage de Tamentfoust','شاطئ تامنطفوست','Tamentfoust Beach'],
    ['Plage de Bordj El Bahri','شاطئ برج البحري','Bordj El Bahri Beach'],
    ['Plage de Staouëli','شاطئ الصطاوالي','Staouëli Beach'],
    ['Plage de Réghaïa','شاطئ الرغاية','Réghaïa Beach'],
    ['Plage de Khemisti','شاطئ الخميستي','Khemisti Beach'],
    ['Plage de Gué de Constantine','شاطئ قسنطينة','Gué de Constantine Beach'],
    ['Plage de Fouka','شاطئ فوكة','Fouka Beach'],
    ['Plage de Sidi Fredj','شاطئ سيدي فرج','Sidi Fredj Beach'],
    ['Plage de Ain Benian','شاطئ عين البنيان','Ain Benian Beach'],
    ['Plage de Cherchell','شاطئ شرشال','Cherchell Beach'],
    ['Plage de Tipaza','شاطئ تيبازة','Tipaza Beach'],
    ['Plage de Hadjout','شاطئ الحجوط','Hadjout Beach'],
    ['Plage de Attatba','شاطئ العطاطبة','Attatba Beach'],
    ['Plage de Sidi Moussa','شاطئ سيدي موسى','Sidi Moussa Beach'],
    ['Plage de Ain Defla','شاطئ عين الدفلى','Ain Defla Beach'],
  ],
  'Oran': [
    ['Plage de Aïn El Turck','شاطئ عين الترك','Aïn El Turck Beach'],
    ['Plage de Bomo','شاطئ بومو','Bomo Beach'],
    ['Plage de Kristel','شاطئ كريستيل','Kristel Beach'],
    ['Plage de Madagh','شاطئ مداغ','Madagh Beach'],
    ['Plage de Trouville Oran','شاطئ تروفيل وهران','Trouville Beach Oran'],
    ['Plage de Canastel','شاطئ قناستيل','Canastel Beach'],
    ['Plage de Saint-Germain','شاطئ سان جيرمان','Saint-Germain Beach'],
    ['Plage de Marsa Ben Mhidi','شاطئ مرسى بن مهيدي','Marsa Ben Mhidi Beach'],
    ['Plage de Bouzedjar','شاطئ بوزجار','Bouzedjar Beach'],
    ['Plage de Ghazaouet','شاطئ الغزوات','Ghazaouet Beach'],
    ['Plage de Cap Falcon','شاطئ كاب فالكون','Cap Falcon Beach'],
    ['Plage de Mostaganem','شاطئ مستغانم','Mostaganem Beach'],
    ['Plage de Sidi Lakhdar','شاطئ سيدي لخضر','Sidi Lakhdar Beach'],
    ['Plage de Sassel','شاطئ ساسل','Sassel Beach'],
    ['Plage de Terga','شاطئ تارقة','Terga Beach'],
    ['Plage de Honaïne','شاطئ هنين','Honaïne Beach'],
    ['Plage de Arbal','شاطئ العربال','Arbal Beach'],
    ['Plage de Les Andalouses','شاطئ الأندلسيات','Les Andalouses Beach'],
    ['Plage de Rachgoun','شاطئ راشقون','Rachgoun Beach'],
    ['Plage de Cap Falcon Sud','شاطئ كاب فالكون جنوب','Cap Falcon Sud Beach'],
  ],
  'Annaba': [
    ['Plage de Chapuis','شاطئ شابوي','Chapuis Beach'],
    ['Plage de La Caroube','شاطئ الخروب','La Caroube Beach'],
    ['Plage de Seraïdi','شاطئ سرايدي','Seraïdi Beach'],
    ['Plage de Chetaïbi','شاطئ شطايبي','Chetaïbi Beach'],
    ['Plage de El Bahri Annaba','شاطئ البحري عنابة','El Bahri Beach Annaba'],
    ['Plage de Ras El Hamra','شاطئ رأس الحمراء','Ras El Hamra Beach'],
    ['Plage de Oued El Aneb','شاطئ واد العناب','Oued El Aneb Beach'],
    ['Plage de Ain Achir','شاطئ عين أشير','Ain Achir Beach'],
    ['Plage de Tréat','شاطئ تريات','Tréat Beach'],
    ['Plage de Sidi Salem Annaba','شاطئ سيدي سالم عنابة','Sidi Salem Beach Annaba'],
    ['Plage de La Forêt','شاطئ الغابة','La Forêt Beach'],
    ['Plage de Chiba','شاطئ شيبة','Chiba Beach'],
    ['Plage de Oued El Boudjemaa','شاطئ واد البوجمعة','Oued El Boudjemaa Beach'],
    ['Plage de Mesloula','شاطئ مسلولة','Mesloula Beach'],
    ['Plage de Hadjret Ennous','شاطئ حجرة النواس','Hadjret Ennous Beach'],
    ['Plage de Kef El Akhal','شاطئ كاف الأكحل','Kef El Akhal Beach'],
    ['Plage de Oued Zied','شاطئ واد زيد','Oued Zied Beach'],
    ['Plage de Skikda Route','شاطئ طريق سكيكدة','Skikda Route Beach'],
    ['Plage de Berrahal Annaba','شاطئ برحال عنابة','Berrahal Beach Annaba'],
    ['Plage de Ain Barbar','شاطئ عين بربر','Ain Barbar Beach'],
  ],
  'Béjaïa': [
    ['Plage de Boulimat','شاطئ بوليمات','Boulimat Beach'],
    ['Plage de Tichy','شاطئ تيشي','Tichy Beach'],
    ['Plage de Aokas','شاطئ أوقاس','Aokas Beach'],
    ['Plage de Melbou','شاطئ مالبو','Melbou Beach'],
    ['Plage de Souk El Tenine','شاطئ سوق الإثنين','Souk El Tenine Beach'],
    ['Plage de Toudja','شاطئ توجة','Toudja Beach'],
    ['Plage de Corniche des Falaises','شاطئ كورنيش الجرف','Corniche des Falaises Beach'],
    ['Plage de La Casbah Béjaïa','شاطئ القصبة بجاية','La Casbah Beach Béjaïa'],
    ['Plage de Aamriw','شاطئ عمريو','Aamriw Beach'],
    ['Plage de Boukhlifa','شاطئ بوخليفة','Boukhlifa Beach'],
    ['Plage de Tala Ilane','شاطئ تالة إيلان','Tala Ilane Beach'],
    ['Plage de Ighil Izane','شاطئ إغيل إيزان','Ighil Izane Beach'],
    ['Plage de Bejaia Est','شاطئ بجاية الشرقي','Bejaia East Beach'],
    ['Plage de Kherrata Gorges','شراجة خراطة','Kherrata Gorges'],
    ['Plage de Adekar Rivière','شاطئ نهر أدكار','Adekar River Beach'],
    ['Plage de Sidi Aïch','شاطئ سيدي عيش','Sidi Aïch Beach'],
    ['Plage de Barbacha Oued','شاطئ نهر بربوش','Barbacha River Beach'],
    ['Plage de Soummam Rivière','شاطئ نهر الصومام','Soummam River Beach'],
    ['Plage de Bejaia Saket','شاطئ صاكت بجاية','Saket Beach Béjaïa'],
    ['Plage de Amizour Lac','بحيرة أميزور','Amizour Lake'],
  ],
  'Tizi Ouzou': [
    ['Plage de Tigzirt','شاطئ تيقزيرت','Tigzirt Beach'],
    ['Plage de Iflissen','شاطئ إفليسن','Iflissen Beach'],
    ['Plage de Azzefoun','شاطئ أزفون','Azzefoun Beach'],
    ['Plage de Aït Chaffaâ','شاطئ آث شفعة','Aït Chaffaâ Beach'],
    ['Plage de Larbaâ Nath Irathen','شاطئ أربعاء ناث إيراثن','Larbaâ Nath Irathen Lake'],
    ['Plage de Oued Aissi','شاطئ واد عيسي','Oued Aissi River Beach'],
    ['Plage de Djurdjura Lac','بحيرة الجرجرة','Djurdjura Lake'],
    ['Plage de Sidi Naâmane','شاطئ سيدي نعمان','Sidi Naâmane Beach'],
    ['Plage de Tabouda','شاطئ طبودة','Tabouda Beach'],
    ['Plage de Ait Yahia Moussa','شاطئ آث يحيى موسى','Ait Yahia Moussa Beach'],
    ['Plage de Oued Boubhir','شاطئ واد بوبهير','Oued Boubhir Beach'],
    ['Plage de Iwakouren','شاطئ إواكورن','Iwakouren Beach'],
    ['Plage de Aghribs','شاطئ أغريب','Aghribs Beach'],
    ['Plage de Beni Zmenzer Lac','بحيرة بني زمنزر','Beni Zmenzer Lake'],
    ['Plage de Oued Tizi','شاطئ واد تيزي','Oued Tizi Beach'],
    ['Plage de Fréha Rivière','شاطئ نهر فريحة','Fréha River Beach'],
    ['Plage de Sidi Ali Bounab','شاطئ سيدي علي بوناب','Sidi Ali Bounab Beach'],
    ['Plage de Bouzeguene','شاطئ بوزقن','Bouzeguene Beach'],
    ['Plage de Zekri Rivière','شاطئ نهر زكري','Zekri River Beach'],
    ['Plage de Illilten Lac','بحيرة إيليلتن','Illilten Lake'],
  ],
  'Tlemcen': [
    ['Plage de Marsa Ben Mhidi Tlemcen','شاطئ مرسى بن مهيدي تلمسان','Marsa Ben Mhidi Beach Tlemcen'],
    ['Plage de Honaine','شاطئ هنين','Honaine Beach'],
    ['Plage de Bouzedjar Tlemcen','شاطئ بوزجار تلمسان','Bouzedjar Beach Tlemcen'],
    ['Plage de El Ghazaouet Tlemcen','شاطئ الغزوات تلمسان','El Ghazaouet Beach Tlemcen'],
    ['Plage de Oued Mouilah','شاطئ واد المويلح','Oued Mouilah River'],
    ['Plage de Tafna Rivière','شاطئ نهر تافنة','Tafna River Beach'],
    ['Lac de Cavallo Tlemcen','بحيرة كافالو تلمسان','Cavallo Lake Tlemcen'],
    ['Lac de Zenata Tlemcen','بحيرة زناتة تلمسان','Zenata Lake Tlemcen'],
    ['Plage de Sidi Ali Benyoub','شاطئ سيدي علي بن يوب','Sidi Ali Benyoub Beach'],
    ['Plage de Remchi Rivière','شاطئ نهر رمشي','Remchi River Beach'],
    ['Lac de Sebdou','بحيرة سبدو','Sebdou Lake'],
    ['Plage de Ain Youcef','شاطئ عين يوسف','Ain Youcef Beach'],
    ['Lac de Beni Saf Tlemcen','بحيرة بني صاف تلمسان','Beni Saf Lake Tlemcen'],
    ['Plage de Nedroma Rivière','شاطئ نهر ندرومة','Nedroma River Beach'],
    ['Cascade de Tlemcen','شلال تلمسان','Tlemcen Waterfall'],
    ['Oued Chouly Tlemcen','واد شولي تلمسان','Oued Chouly Tlemcen'],
    ['Source de Ain Ghoraba','عين غرابة','Ain Ghoraba Spring'],
    ['Plage de Maghnia Barrage','شاطئ سد مغنية','Maghnia Dam Beach'],
    ['Lac de Ain Fezza','بحيرة عين الفضة','Ain Fezza Lake'],
    ['Oued Isser Tlemcen','واد إيسر تلمسان','Oued Isser Tlemcen'],
  ],
};

function shortDesc(category, nameFr, wilaya) {
  const descs = {
    restaurants: `Cuisine traditionnelle algérienne dans un cadre authentique à ${wilaya}. Spécialités locales, produits frais et ambiance chaleureuse.`,
    salons: `Salon de thé et pâtisserie orientale à ${wilaya}. Thé à la menthe, gâteaux au miel et café à l'italienne dans un cadre convivial.`,
    artisanat: `Boutique artisanale à ${wilaya} proposant des créations traditionnelles et contemporaines faites main par des artisans locaux.`,
    plages: `Site naturel aquatique à ${wilaya}. Eaux cristallines, panorama exceptionnel et cadre naturel préservé idéal pour la détente.`,
  };
  return descs[category] || `${nameFr} à ${wilaya}.`;
}

function shortDescAr(category, wilaya) {
  const descs = {
    restaurants: `مطبخ جزائري تقليدي في إطار أصيل بـ${wilaya}. تخصصات محلية ومنتجات طازجة وأجواء دافئة.`,
    salons: `صالون شاي وحلويات شرقية بـ${wilaya}. شاي بالنعناع وحلويات بالعسل وقهوة إيطالية في جو مريح.`,
    artisanat: `محل للحرف التقليدية بـ${wilaya} يقدم إبداعات يدوية لأحرفيين محليين.`,
    plages: `موقع طبيعي مائي بـ${wilaya}. مياه صافية ومناظر خلابة وإطار طبيعي محفوظ مثالي للراحة.`,
  };
  return descs[category] || `موقع في ${wilaya}.`;
}

function shortDescEn(category, wilaya) {
  const descs = {
    restaurants: `Traditional Algerian cuisine in an authentic setting in ${wilaya}. Local specialties, fresh produce and a warm atmosphere.`,
    salons: `Tea salon and oriental pastry in ${wilaya}. Mint tea, honey cakes and Italian coffee in a friendly setting.`,
    artisanat: `Artisan shop in ${wilaya} offering handmade traditional and contemporary creations by local craftspeople.`,
    plages: `Natural water site in ${wilaya}. Crystal-clear waters, exceptional panorama and preserved natural setting ideal for relaxation.`,
  };
  return descs[category] || `${wilaya} site.`;
}

function catImages(category, nameFr) {
  const base = {
    restaurants: ['restaurant,algerian,food','traditional,cuisine,table','moroccan,dining,couscous'],
    salons: ['tea,salon,mint','oriental,cafe,pastry','coffee,arabic,traditional'],
    artisanat: ['craft,artisan,handmade','traditional,workshop,algeria','souvenir,art,local'],
    plages: ['beach,algeria,sea','mediterranean,coast,clear','algerian,beach,summer'],
  };
  return (base[category] || ['algeria,place']).map(q => `https://source.unsplash.com/800x500/?${q}`);
}

let output = '';
let count = 0;

wilayas.forEach(w => {
  const cats = ['restaurants', 'salons', 'artisanat', 'plages'];
  cats.forEach(cat => {
    let names;
    if (cat === 'restaurants') names = restaurantNames[w.name];
    else if (cat === 'salons') names = salonNames[w.name];
    else if (cat === 'artisanat') names = artisanatNames[w.name];
    else names = plageNames[w.name];

    names.forEach((entry, i) => {
      const [nameFr, nameAr, nameEn, craftType] = entry;
      const idx = String(i + 1).padStart(2, '0');
      const catShort = { restaurants: 'rest', salons: 'sal', artisanat: 'art', plages: 'plg' }[cat];
      const id = `${w.prefix}_${catShort}_n${idx}`;
      const lat = r(w.lat, 0.15);
      const lon = r(w.lon, 0.15);
      const rating = (3.8 + Math.random() * 1.1).toFixed(1);
      const reviews = rInt(120, 2800);
      const pop = rInt(55, 90);
      const images = catImages(cat, nameFr);
      const desc = shortDesc(cat, nameFr, w.name);
      const descAr = shortDescAr(cat, w.name);
      const descEn = shortDescEn(cat, w.name);
      const craftStr = craftType ? `, craftType: "${craftType}"` : '';
      const openHours = cat === 'plages' ? '' : `, openingHours: "${cat === 'restaurants' ? '12h-23h' : '08h-22h'}"`;

      output += `    { id: "${id}", nameFr: "${nameFr}", nameAr: "${nameAr}", nameEn: "${nameEn}", name: "${nameFr}", category: "${cat}", wilaya: "${w.name}", wilayaCode: ${w.code}, description: "${desc}", descriptionAr: "${descAr}", descriptionEn: "${descEn}", images: ${JSON.stringify(images)}, address: "${w.name}", latitude: ${lat}, longitude: ${lon}, googleRating: ${rating}, googleReviewCount: ${reviews}, googlePlaceId: "${id}_gp", popularity: ${pop}, isFeatured: false${openHours}${craftStr} },\n`;
      count++;
    });
  });
});

console.log(`Generated ${count} places`);

// Insert into places.service.ts
const filePath = '/home/dg6497/projects/GoDZ/src/app/services/places.service.ts';
const content = fs.readFileSync(filePath, 'utf8');
const marker = '  ] as Place[]).sort(';
const idx = content.indexOf(marker);
if (idx === -1) { console.error('Marker not found!'); process.exit(1); }
const newContent = content.slice(0, idx) + output + content.slice(idx);
fs.writeFileSync(filePath, newContent, 'utf8');
console.log('Inserted into places.service.ts');
